// Generated by CoffeeScript 1.7.1
(function() {
  var __slice = [].slice;

  Function.prototype.compose = function(g) {
    var comp, f;
    f = this;
    comp = null;
    (function(f) {
      return comp = function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return f(g.apply(null, args));
      };
    })(f);
    return comp;
  };

}).call(this);
