// Generated by CoffeeScript 1.7.1
(function() {
  var World,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  World = (function() {
    function World(map) {
      this.map = map;
    }

    World.prototype.entities = [];

    World.prototype.addDrone = function(x, y, options) {
      var drone;
      drone = new Drone(this.map);
      if (options) {
        if (__indexOf.call(options.special, 'unlimited energy') >= 0) {
          drone.energy = 10000000;
        }
        if (__indexOf.call(options.special, 'test') >= 0) {
          drone.loadCode(CodeParser.testCode);
        }
      }
      this.entities.push(drone);
      drone.x = x;
      return drone.y = y;
    };

    World.prototype.tick = function() {
      var entity, _i, _len, _ref, _results;
      _ref = this.entities;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        entity = _ref[_i];
        _results.push(entity.tick());
      }
      return _results;
    };

    World.prototype.map = null;

    return World;

  })();

  window.World = World;

}).call(this);
